# Generated by Django 5.2.5 on 2026-02-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='B_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
