# Generated by Django 5.2.5 on 2026-02-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_b_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='B_title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
