# Generated by Django 5.2.5 on 2026-02-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_author_remove_book_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
