# Generated by Django 5.2.5 on 2026-02-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_author_date_of_birth_author_date_of_death'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total',
        ),
        migrations.RemoveField(
            model_name='book',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
