# Generated by Django 5.2.5 on 2026-02-07 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_publisher_book_added_by_book_book_type_book_ddc_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='country',
        ),
    ]
