# Generated by Django 5.2.5 on 2026-02-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_librarybranch_book_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shelf_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
