# Generated by Django 5.2.5 on 2026-02-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_book_shelf_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ddc_no',
        ),
        migrations.RemoveField(
            model_name='book',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='book',
            name='library',
        ),
        migrations.RemoveField(
            model_name='book',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publishing_year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='shelf_no',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_volumes',
        ),
    ]
