# Generated by Django 5.2.5 on 2026-02-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_remove_book_added_by_remove_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
