# Generated by Django 5.2.5 on 2026-02-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_book_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_volumes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
