# Generated by Django 5.2.5 on 2026-02-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_book_total_volumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('borrowed', 'Borrowed'), ('reserved', 'Reserved'), ('lost', 'Lost')], default='draft', max_length=20),
        ),
    ]
