# Generated by Django 5.2.5 on 2026-02-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
