# Generated by Django 5.2.5 on 2026-02-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_remove_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('borrowed', 'Borrowed'), ('reserved', 'Reserved'), ('lost', 'Lost')], default='draft', max_length=20),
        ),
    ]
