# Generated by Django 5.2.5 on 2026-04-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_remove_book_language_remove_book_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='date_of_inclusion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='no_of_copy',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='shelf_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
